### ISSUE TITLE
Message with New Line Function

### ISSUE THREAD

**Issue by Sound-Techniker** [bitfocus/companion-module-telegram-bot#2]
Hello i would like Send messages with Telegram bot with new line Funktion.

i try´d "\n" but this does not work

**Comment by leonreucher** [comment]
Hey there,

sorry, I didn't see the issue. I tried everything for now but can't get the Telegram API to process any new line codes. The only thing which worked for me is to copy the next line symbol and directly enter it into the text field:

http://www.unicode-symbol.com/u/0085.html#google_vignette

**Comment by Archimede2** [comment]
@leonreucher 

Hello could you give us an example of how you have right your message because I can't find the good syntax to make it work with just a u0085.
I indeed teste this:
"Votre premier message \u0085 Votre deuxième message"
But it did not work. 

Thanks a lot for your answer.

**Comment by leonreucher** [comment]
http://www.unicode-symbol.com/u/0085.html#google_vignette)

Just copy the symbol from the page (you can select the symbol shown on the page) and paste it into companion. Not beautiful, but works for me.

**Comment by Archimede2** [comment]
Thank you very much for the advice 

Indeed, its a strange way but at least, it's work
